<?php
    use PayRoll\controllers\sites\SitesController;
    $modulos = new SitesController();
?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>.:Nómina:.</title>
</head>
<body>
    <?php include realpath('./src/views/includes/header.phtml'); ?>
    <?php include realpath('./src/views/includes/menu.phtml'); ?>
    <section>
        <?php $modulos->obtenerModulos();?>    
    </section>
</body>
</html>