<div class="patria">
    <!--<h1>Patria</h1>-->
    <div class="wrapperform">
        <form id="form-patria" method="post">
            <div class="line">
                <input type="text" size="40" id="nbNumero" name="nbNumero" pattern="[0-9]{4}" required placeholder="Ingresa el código nómina" />
            </div>
            <div class="line">
                <input type="text" size="40" id="txtDesnom" placeholder="Descripción de la nómina" name="txtDesnom" readonly  />
            </div>
            <div class="line">
                <button type="submit">Generar TXT</button>
            </div>
        </form>        
    </div>    
</div>
<!--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-->